### ISSUE TITLE
ADS-sum commands?

### ISSUE THREAD

**Issue by Lyriumbyte** [stlehmann/pyads#108]
Is there a possibility to do sum commands? See: https://infosys.beckhoff.com/english.php?content=../content/1033/tcsample_vc/html/tcadsdll_api_cpp_sample17.htm&id

**Comment by stlehmann** [comment]
At the moment sum-commands are not supported for pyads. However, this seems to be a nice feature. You are very welcome to elaborate on it.

**Comment by stlehmann** [comment]
Thanks again @bdcoyle for implementing this feature.
