### ISSUE TITLE
adserror server not started (6) target port not found

### ISSUE THREAD

**Issue by amarco** [stlehmann/pyads#109]
I am at a loss. From my XAEshell enviroment I can connect to my plc and download code, debug code rune code on the plc. But when I try to access the plc from pyads from the same windows computer as xae I get an adserror about server not started and port not found. I see I am connectd to the plc from within routes on the windows pc. 
What am I missing?

Marco

**Comment by kryskool** [comment]
Hi @amarco 

can you show us your code ?

regards,

**Comment by amarco** [comment]
Code is really basic and based on examples.

import pyads

plc=pyads.Connection('10.10.32.225.1.1',pyads.PORT_SPS1)
plc.open()

#this returns true
print("Opened PLC {0}".format(plc.is_open))

#this fails
info=plc.read_device_info()
print("PLC Info {0}".format(info))

#this fails as well
fastFrameBufferReady = plc.read_by_name("GVL.ioList.fastFrameBufferReady",pyads.PLCTYPE_BOOL)
print("FastFrameBufferReady {0}".format(fastFrameBufferReady))

**Comment by amarco** [comment]
after exploring further I started to look at why it would not communicate so I was looking at port number and noticed that PORT_SPS1 is for TwinCat 2 and I am using TwinCat 3 so I change to PORT_TC3PLC1 and things started to work. I also then had to remove the reference to GVL to get the read to actually return a value.

**Comment by stlehmann** [comment]
So this issue can be closed?

**Comment by amarco** [comment]
Yes I closed the ticket, sorry for that..
