### ISSUE TITLE
Read out all available names

### ISSUE THREAD

**Issue by windelbouwman** [stlehmann/pyads#115]
Just wanted to let you know that @phectori used this library to read out all variables from a PLC.

See the resulting script here: https://github.com/windelbouwman/lognplot/blob/master/adapters/ads_adapter.py

Is there any way this feature could be added to pyads?

**Comment by stlehmann** [comment]
This could be a cool feature. Would you loke to make a PR for it?

**Comment by windelbouwman** [comment]
This sounds like a good plan, @phectori what do you think?

**Comment by stlehmann** [comment]
This feature is covered with #155
