### ISSUE TITLE
import pyads error ,  can't import Type   'from typing import Type'

### ISSUE THREAD

**Issue by yanbin-ha** [stlehmann/pyads#126]
import pyads error ,  can't import Type   'from typing import Type'

**Comment by stlehmann** [comment]
Thanks for your feedback. But would you mind to provide just a tiny bit of more information to your post. It is very hard for us to guess the side-effects of your error. Please post your current Python version, the complete traceback and most important some text that describes your problem. Thank you.

**Comment by yanbin-ha** [comment]
Thanks for your reply
I solved this problem myself，because python 3.5.0 has no  class Type in typing. so i update python version to 3.5.6 .. now it can work

**Comment by stlehmann** [comment]
Great you could work this out and thanks for the feedback.
