### ISSUE TITLE
Notification parsing

### ISSUE THREAD

**Issue by corylutton** [stlehmann/pyads#143]
Thanks for such a useful library.  I am in the middle of using it to subscribe to tags and forward the messages to MQTT.  In doing so, I noticed that converting the notification to the python object is available via a decorator.  Since I keep a subscriptions dict with their datatype, I have copied the guts of that notification decorator in order to do conversion as needed which simplifies the amount of code required.. my question is if you would be interested in a pull request to have the notification parsing available without using the decorator syntax?

For example you show using the decorator like this:

```
@plc.notification(pyads.PLCTYPE_STRING)
def callback(handle, name, timestamp, value):
    print(handle, name, timestamp, value)
```

I'm proposing making an adjustment that would allow use like this as well:

```
def callback(notification, data):
    datatype = my_subscriptions(data)
    result = self.notification_parse(notification, datatype, data)
    # result here would be (contents.hNotification, data_name, timestamp, value) which would preserve current funtion
```

I would probably just move the guts of the decorator to a helper function called notification_parse on the connection instance which would just open that bit of code for decorator or the use case I propose.  This might also make it easier in the future to automatically do that conversion by keeping track of the notifications requested...

Please let me know if there would be interest in a pull request like that and thanks again for the useful library.

Thanks
Cory Lutton

**Comment by stlehmann** [comment]
@corylutton I'm glad you like the library. I would gladly accept a PR concerning this matter so feel free to go for it.
