### ISSUE TITLE
Docker: adslib.so: invalid ELF header

### ISSUE THREAD

**Issue by ChristianHemann** [stlehmann/pyads#147]
hey,
I'm trying to automate the build process for my own python package which is using pyads. The build-pipeline is using Linux Docker images. When I try to import pyads within that container I get the following error:
```
>>> import pyads

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/pyads/__init__.py", line 12, in <module>
    from .ads import open_port, close_port, get_local_address, read_state, \
  File "/opt/conda/lib/python3.7/site-packages/pyads/ads.py", line 18, in <module>
    from .pyads_ex import (
  File "/opt/conda/lib/python3.7/site-packages/pyads/pyads_ex.py", line 82, in <module>
    _adsDLL = ctypes.CDLL(adslib)
  File "/opt/conda/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/lib/python3.7/site-packages/pyads/adslib.so: invalid ELF header
```

I installed pyads via `pip install pyads`. This worked for me after I added cmake to my Dockerfile (which installs gcc as well)

My Dockerfile looks like this:
```
FROM continuumio/miniconda3:4.8.2
WORKDIR ~
RUN apt-get update && apt-get -y install curl cmake && apt-get clean

RUN conda install --freeze-installed -c anaconda nomkl numpy jupyter pyzmq opencv conda-build sphinx \
    && conda clean -afy \
    && find /opt/conda/ -follow -type f -name '*.pyc' -delete \
    && find /opt/conda/ -follow -type f -name '*.js.map' -delete
```

According to this issue I think the problem is how the lib was built, but I am not familiar with that process:
[https://github.com/stlehmann/pyads/issues/36](https://github.com/stlehmann/pyads/issues/36)

Is there a way to solve that issue or is it too specific to docker?

**Comment by stlehmann** [comment]
@ChristianHemann Which architecture are you using? pyads does not work on ARM

**Comment by stlehmann** [comment]
I'll close this for now. Feel free to pick up on this issue if anything has changed.

**Comment by mh7d** [comment]
I just had the same problem installing pyads on a Raspberry Pi 4 using buster. I could fix it by building and installing it locally like described here: https://pyads.readthedocs.io/en/latest/installation.html#installation-on-linux

Seems like the automatic process using pip is the only problem.
