### ISSUE TITLE
Change in Variables

### ISSUE THREAD

**Issue by Abhishek81723** [stlehmann/pyads#167]
Hello,

I am working on a project with TwinCat and AMR. I am using python as communication medium between the two systems. I have an issue of waiting for the variable to change value. I have a variable of type 'BOOL' and want to perform certain action when the variable changes, Can someone help me with this? P.S. I have notified for change in variable as well.

 StnF = PLC.read_by_name('GVL.AGVgotoStnF', pyads.PLCTYPE_BOOL)
 print(StnF)

if StnF == 'TRUE' :
 ArrStnF = PLC.write_by_name('GVL.iPosAGV',3,pyads.PLCTYPE_INT)
 print(ArrStnF)

**Comment by stlehmann** [comment]
Abhishek81723 I'm sorry but Github issues is not the right place to ask for help on using this package. Please use communities like Stackoverflow for this. Kind Regards.
