### ISSUE TITLE
read/write_structure_by_name containing boolean values

### ISSUE THREAD

**Issue by eliasganthaler** [stlehmann/pyads#171]
Dear all,

I try to read a structe containig tuples of different datatypes. I have problems reading and writing tuples containig boolean values. 
From what I understand is pyads reading the values byte-wise, but a boolean value has a length of 1 bit.
Is there a possibility to read such a structure?

**Comment by stlehmann** [comment]
@eliasganthaler Please use a forum like stackoverflow for questions concerning the usage of pyads.
