### ISSUE TITLE
Duplicate classes for TestServer and Handlers

### ISSUE THREAD

**Issue by RobertoRoos** [stlehmann/pyads#173]
Just noticed there is a class `Testserver` defined in 'pyads/testserver_ex/server.py' and a class `AdsTestServer` in 'pyads/testserver.py'.  
Similarly, there is a class `AdvancedHandler` in 'pyads/testserver.py' and a class `AdvancedHandler` in 'pyads/testserver_ex/handler.py'.

Is there a reason for these duplicates? It's a little confusing.

Edit:  
It seems `testserver_ex.handler.AdvancedHandler` is only used by `testserver_ex.server.Testserver`. And `testserver_ex.server.Testserver` doesn't seem to be used outside it's own file.

**Comment by stlehmann** [comment]
Yes testserver_ex contains the prototype of an advanced testserver that can store values and returns them on write / read operations. I never managed to finish this prototype so it is still not used in any tests.

**Comment by RobertoRoos** [comment]
Ah, right. I thought that maybe it was the opposite: a left over from older versions.

Note that I patched the existing AdvancedHandler in https://github.com/stlehmann/pyads/pull/174, maybe some of it could be helpful.

**Comment by stlehmann** [comment]
@RobertoRoos Which classes do you mean pricesely?

**Comment by RobertoRoos** [comment]
There are [testserver.AdsTestServer](https://github.com/stlehmann/pyads/blob/master/pyads/testserver.py#L79) and [testserver_ex.server.Testserver](https://github.com/stlehmann/pyads/blob/master/pyads/testserver_ex/server.py#L36)

And [testserver.AdvancedHandler](https://github.com/stlehmann/pyads/blob/master/pyads/testserver.py#L624) and [testserver_ex.handler.AdvancedHandler](https://github.com/stlehmann/pyads/blob/master/pyads/testserver_ex/handler.py#L35)

Just to emphasize: I am not at all against improving the testserver or switching to a new approach, but I don't think an unfinished or unused feature belongs in the production branch.

**Comment by stlehmann** [comment]
I'm with you in this matter. If I remember right I created the testserver_ex package to bring more order in the testerver module. So the overall goal would be to replace the simple testserver module by this package. Maybe a way to go about would be to put testserver_ex in a new branch called "testserver_ex" to have a clean master branch as you suggested. What do you think?

**Comment by RobertoRoos** [comment]
Yeah, let's do that.

**Comment by stlehmann** [comment]
Thanks @RobertoRoos for getting this done.
