### ISSUE TITLE
Close pyads.Connection in destructor

### ISSUE THREAD

**Issue by RobertoRoos** [stlehmann/pyads#178]
Mentioned this in #174, but I figured it deserves its own issue.

The `Connection` class currently does not have a destructor. I figured it might make sense to close it in `__del__`. If it's already closed it can't do any harm. Is there a reason this was not added?

**Comment by stlehmann** [comment]
>  I figured it might make sense to close it in __del__. 

You mean to close the connection if the object is destroyed? This is a great idea. It think the main reason why it has not been added is because nobody thought of it, yet.

**Comment by RobertoRoos** [comment]
Lemme get a new PR rolling.
