### ISSUE TITLE
Is read the docs updated correctly?

### ISSUE THREAD

**Issue by chrisbeardy** [stlehmann/pyads#196]
I saw you made a new release yesterday which updated all the docs, however looking at readthedocs, they do not seem to be displaying correctly?

![2021-02-13-174401_1920x1080_scrot](https://user-images.githubusercontent.com/20585410/107856954-8ccba880-6e23-11eb-94bc-4e8421f51f0f.png)

**Comment by chrisbeardy** [comment]
nice work on the docs btw.

**Comment by stlehmann** [comment]
@chrisbeardy thanks. Looks like RTD is still displaying the old version for you. For me it loks different:

![grafik](https://user-images.githubusercontent.com/4641542/107883670-81927e80-6ef0-11eb-811b-6842b447708b.png)

Did you reload the page?

**Comment by chrisbeardy** [comment]
This sorted itself out after you pushed some more commits today.
