### ISSUE TITLE
read_structure_by_name should have `Optional[Union[Dict[str, Any], List[Dict[str, Any]]]]:` for type info?

### ISSUE THREAD

**Issue by chrisbeardy** [stlehmann/pyads#203]
I believe that the `read_structure_by_name` should have `Optional[Union[Dict[str, Any], List[Dict[str, Any]]]]:` for type info.

As this is the return from dict_from_bytes combined with the None return if read_by_name returns None.

**Comment by stlehmann** [comment]
I agree. That is better than Any.

**Comment by stlehmann** [comment]
Solved with #208
