### ISSUE TITLE
Device Notifications emits immediately current value

### ISSUE THREAD

**Issue by ceekay456** [stlehmann/pyads#241]
Hi, 

I have a question with regards to device notifications. 
When adding a device notification, a notification is immediately triggered giving the current value on the PLC although this value is not changed.  

Is there a way to 'ignore' the first value or to config the notification to trigger only on actual changes?

Thanks,
Christophe

**Comment by stlehmann** [comment]
I don't think there is a way to skip the first notification. But you can easily implement that for yourself e.g. by setting a global flag after the first call.
