### ISSUE TITLE
Add PLCTYPE_WSTRING support 

### ISSUE THREAD

**Issue by 1130164523** [stlehmann/pyads#246]
I have implemented the PLCTYPE_WSTRING variable related operations, can I merge it into the main branch? 
我已经实现了 PLCTYPE_WSTRING变量的相关操作，可以合并到主分支吗 ？

**Comment by kryskool** [comment]
Hi @1130164523 

Can you  send a pull request 

Regards,

**Comment by stlehmann** [comment]
This is solved with #274
