### ISSUE TITLE
New testserver submodule missing in release 3.3.5

### ISSUE THREAD

**Issue by RobertoRoos** [stlehmann/pyads#248]
I wanted to try out the new testserver in my application, but

```
from pyads.testserver import AdsTestServer
```

...fails, saying the `testserver` module does not exist.

The installed package contains the following files:

```
.
├── __init__.py
├── ads.py
├── constants.py
├── errorcodes.py
├── filetimes.py
├── pyads_ex.py
├── structs.py
├── symbol.py
└── utils.py
```

So it is missing the new testserver directory.

**Comment by RobertoRoos** [comment]
I'm a dumbass, it hasn't been merged yet... I thought that with the version bump it had...

I wish Github had a commits tree view like Bitbucket does.

**Comment by RobertoRoos** [comment]
Okay, I'm a double-dumbass. It was merged properly, the directory is right here: https://github.com/stlehmann/pyads/tree/3.3.5/pyads/testserver

So then there is a pypi problem. You can see the latest package is missing the new files: https://pypi.org/project/pyads/#files

**Comment by RobertoRoos** [comment]
Tested this locally using `pip install .` and I can reproduce this problem that way.

I think I fixed it with adding the submodule in `setup.py`:
```
setup(
    # ....
    packages=["pyads", "pyads.testserver"],
```

But I've no clue whether this is conventional.

**Comment by RobertoRoos** [comment]
The internet suggests it too: https://stackoverflow.com/questions/26528178/right-way-to-set-python-package-with-sub-packages

@stlehmann what do you think?

**Comment by stlehmann** [comment]
@RobertoRoos Thanks for making the PR. I merged it right away.
