### ISSUE TITLE
read_list_by_name generates "ADSError: parameter size not correct (1797)." but write_list works

### ISSUE THREAD

**Issue by ako-kft** [stlehmann/pyads#257]
Stefan,  first of all: fantastic work! This little module got me right out of the blocks. 

I stumbled upon an issue I am unable to resolve:  

![image](https://user-images.githubusercontent.com/52218625/125522972-e8a42d9a-23a6-4375-8eb6-9c92d5e154e8.png)

read_by_name, write_by_name both work just fine. Any ideas what read_list_by_name is complaining about?

My host machine is Ubuntu 20.04, my PLC is a TwinCAT3 machine.

Thank you for your support! Best regards, Adrian

PS: I am obviously too dumb to get  code snippets to format properly... (facepalm) I apologize for the picture.

**Comment by chrisbeardy** [comment]
I think this is the same issue as #232 . Therefore can i polielty ask you to close this issue and we can track it through #232.

**Comment by ako-kft** [comment]
Agreed. -Adrian
