### ISSUE TITLE
Incomplete ADS return codes

### ISSUE THREAD

**Issue by auen** [stlehmann/pyads#313]
errorcodes.py does not contain ADS return codes 29 and 30. Ref: [ADS Return Codes](https://infosys.beckhoff.com/english.php?content=../content/1033/devicemanager/374277003.html&id=)

**Comment by kryskool** [comment]
Hi @auen 

Thanks, i create a pull request for these missing code

**Comment by chrisbeardy** [comment]
fixed commit 4a16da3f4c530a0355e1a3025970ab1fd38829a9
