### ISSUE TITLE
 Failed to open port on AMS router

### ISSUE THREAD

**Issue by Summerxiaxia623** [stlehmann/pyads#316]
My PLC works fine with TwinCat. However, when I follow the tutorial of pyads: plc.open(), I always get the the RuntimeError: Failed to open port on AMS router. 
I already checked the AmsNetId, ip address. 

Thank you for you suggestion!

**Comment by chrisbeardy** [comment]
Have you followed the instructions for creating a route? https://pyads.readthedocs.io/en/latest/documentation/routing.html

**Comment by chrisbeardy** [comment]
If you are running pyads on the same windows pc as TwinCat is running on then please follow my advice in #315

**Comment by chrisbeardy** [comment]
@stlehmann @Summerxiaxia623 can this be closed?
