### ISSUE TITLE
Segmentation Fault core dumped after closeing multiple connections

### ISSUE THREAD

**Issue by Bavop** [stlehmann/pyads#317]
Hello,
I am writing a prgram that connects to multiple plcs at once. For this i have create a class. I wanted to implement a restart functoion in wich i would stop all the plc (.close() ) and then i would reconnect the all (.open()) but after i close the first connection i get a segmentation fault (core dumped). 
![Screenshot_20220420-225909_Termius](https://user-images.githubusercontent.com/54897286/164321870-1edc1bc2-6984-406b-9e04-15ea82f1b5dd.jpg)
SPKAAL and GR17A are names of the plcs

**Comment by chrisbeardy** [comment]
This is likely linked to #256 and i think is an issue with the ADS library on linux. You may have to find a workaround or may not be able to use linux to connect to multiple systems.
