### ISSUE TITLE
Pyads connection refused with Beckhoff Twincat 3

### ISSUE THREAD

**Issue by rudy93** [stlehmann/pyads#333]
Hello,

I am trying to make a connection from a server to a Beckhoff PLC with TwinCAT 3. With Windows everything works fine but with the same server on Linux I can't get a connection. The server has a static IP and in the route manager in the PLC I can find the route and see the server. I have tried adding the route by the route manager in the PLC and with "add_route_to_plc" but both ways my connection is refused. I have already turned off all firewalls. Any of you guys any idea what goes wrong here? In the attachment I have added some picture to see my settings and code.
![afe38e7c-7c05-4c62-94ac-deba06c88042](https://user-images.githubusercontent.com/3979385/200672510-4d69b5df-f647-4cbe-b0e1-cdaf897e4b38.jpg)
![328dc85c-c1a6-40f8-9827-d4ff997ee3c1](https://user-images.githubusercontent.com/3979385/200672534-c6a1b982-c9f3-45e1-b2ae-39844d0e3481.jpg)
![8dc6f7e3-6247-4605-b1bb-d58445210487](https://user-images.githubusercontent.com/3979385/200672537-31ffc36d-1cde-4e63-9ac9-48e8654fec44.jpg)
![a1775f33-8185-485c-b403-933edd4de955](https://user-images.githubusercontent.com/3979385/200672540-e53ad2b6-49be-4b85-8cc5-32431e387981.jpg)
![ab57a5f7-1b99-4299-9fe3-48ff1a8604dc](https://user-images.githubusercontent.com/3979385/200672543-cffe83e6-ba09-46a1-af4d-2f4303242705.jpg)
![c64d3b7a-790c-4cce-be09-fcb0ff64e57c](https://user-images.githubusercontent.com/3979385/200672544-ab5119b7-52da-40c6-ac3a-4b451fff2b1c.jpg)

**Comment by rudy93** [comment]
It helps me a bit, I was already scared that it is probably a problem in Linux.... I don't like Windows as a server, that crashes to much in my opinion. Do you maybe know the best place to ask my question?

**Comment by rudy93** [comment]
Just checked: 255.255.255.0, so should be OK

**Comment by rudy93** [comment]
I don't know exactly how, but I solved the problem. We did everything step by step again, and it worked. But I don't need to close the connection every time. I will close the issue! Thanks for all the input.

**Comment by AbdulFaiz123** [comment]
I am Trying to Do the connection as you did , but I am unable to connect I get the same Problem .,
If. you solved it Can you please Explain here
