### ISSUE TITLE
Cannot read data from linux22.04 to window10

### ISSUE THREAD

**Issue by hovandieu** [stlehmann/pyads#341]
I have created a program that reads data of twincat3 program running on windows10 using the program running at linux22.04
![image](https://user-images.githubusercontent.com/37462281/211744711-097e339d-aa11-4422-ad8a-9ea9c809b83a.png)
The router is created successfully and I have created a connection to the program in Twincat3 on my windows 10 machine.
However, when reading data from the program in Twincat3, the error is generated as below:
![image](https://user-images.githubusercontent.com/37462281/211744769-6a6ce656-120d-4c14-9556-691f5a93cdf1.png)
I have turned off the firewall on my windows10 machine but still can't read or write data for the program in Twincat3

**Comment by chrisbeardy** [comment]
It looks like you are creating a connection to the wrong AMS net ID. You should use the NET ID of the PLC in pyads.Connection. 

e.g.

`plc = pyads.Connection("169.254.136.152", 851)`

**Comment by hovandieu** [comment]
![image](https://user-images.githubusercontent.com/37462281/211950207-00785282-0712-4e48-96c3-8e6bed1232b5.png)

169.254.69.79 is IP connect to PLC device
169.254.136.152 is IP from router. In NUC pc run operation sytem linux 22.04 can ping to this ip.



> It looks like you are creating a connection to the wrong AMS net ID. You should use the NET ID of the PLC in pyads.Connection.
> 
> e.g.
> 
> `plc = pyads.Connection("169.254.136.152", 851)`

-> 173.31.128.1.1.1 is AMS NET ID of PLC. i think it correct with syntax of pyads.connection()

**Comment by hovandieu** [comment]
In one network, i have NUC PC run linux 22.04 and create pyADS program to connect with Laptop Window 10 (run Twincat3 has AMS NETID = 173.31.128.1..1.1).
In laptop have 2 IP:
169.254.69.79 is IP connect to PLC device 
169.254.136.152 is IP get from router.

And in Laptop (Twincat3), result when i click Broadcast Search is nothing.
