### ISSUE TITLE
Beckhoff documentation of the C API

### ISSUE THREAD

**Issue by fravizel-dev** [stlehmann/pyads#357]
The Beckhoff documentation link on the first paragraph of the README seems to be dead: http://infosys.beckhoff.com/english.php?content=../content/1033/tcadsdll2/html/tcadsdll_api_overview.htm&id=20557

Is the mentioned C API the same as the C++ API linked under the **TwinCat 3 > Technologies > ADS > ADS-DLL C++** section of the documentation website? If so, the link should be this one:
https://infosys.beckhoff.com/content/1033/tc3_adsdll2/index.html?id=4279787267115190858

**Comment by chrisbeardy** [comment]
thanks, fixed by #379
