### ISSUE TITLE
Communication with Beckhoff virtual machine from another virtual machine

### ISSUE THREAD

**Issue by X-Carolinii-X** [stlehmann/pyads#359]
Hello guys :)
I I try to connect and read data from plc which is running in TwinCat3 BSD machine. I want to connect from another virtual machine  (Linux Ubuntu) using python and pyads module. Here is all stuff and information:

TwinCat3 BSD machine:
![TwinCat3 BSD machine](https://github.com/stlehmann/pyads/assets/79982619/4423a18c-1258-4586-84c3-aa31a3f9103b)

Search adapters information from TwinCat3 on Windows (my local machine):
![search_adapters](https://github.com/stlehmann/pyads/assets/79982619/d5822cf6-0701-42d6-83e4-2bfbc3009f51)

Connection information from TwinCat3 on Windows (my local machine):
![connection_from_TwinCat_on_windows_to_TSB_machine](https://github.com/stlehmann/pyads/assets/79982619/a00c5189-f4a9-410a-8bf2-b0007baa46aa)

Code in python on virtual machine with Linux Ubuntu:
```
import pyads

if __name__ == "__main__":
    remote_plc_ip = '192.168.2.68'
    remote_plc_net_id = '39.215.159.161.1.1'

    SENDER_AMS = '192.168.56.1.1.1'
    HOSTNAME = '192.168.56.1'
    PLC_USERNAME = 'Administrator'
    PLC_PASSWORD = '1'
    PLC_IP = '192.168.2.68'

    pyads.open_port()
    pyads.set_local_address(SENDER_AMS)
    pyads.add_route_to_plc(SENDER_AMS, HOSTNAME, PLC_IP, PLC_USERNAME, PLC_PASSWORD)

    plc = pyads.Connection(remote_plc_net_id, pyads.PORT_TC3PLC1, remote_plc_ip)
    plc.open()

    if plc.is_open:
        print('Plc is open!')

    try:
        plc.read_state()
        print('Connection succeeded')
    except Exception:
        print('Connection failed')

    plc.close()
```

And now when i try run python code i get:
```
Error: Connect TCP socket failed with: 111
Traceback (most recent call last):
  File "/home/carolinii/Projects/energy_institute_scada/scada-server-side/device_servers/ads/test_ads_connection.py", line 18, in <module>
    plc.open()
  File "/home/carolinii/.local/lib/python3.10/site-packages/pyads/connection.py", line 198, in open
    adsAddRoute(self._adr.netIdStruct(), self.ip_address)
  File "/home/carolinii/.local/lib/python3.10/site-packages/pyads/pyads_ex.py", line 167, in wrapper
    return fn(*args, **kwargs)
  File "/home/carolinii/.local/lib/python3.10/site-packages/pyads/pyads_ex.py", line 189, in adsAddRoute
    raise ADSError(error_code)
pyads.pyads_ex.ADSError: ADSError: target port not found   ADS Server not started (6). 
```

Anyone have idea what is wrong?

**Comment by KrystianTolloczko** [comment]
1. Disable firewall in TwinCAT BSD:

`doas service pf stop `

Note: The firewall is automatically re-enabled after each restart. This behavior is ensured by the entry pf_enable="YES" in the rc.conf file.

2. Check and adjust ADS routes manually in TwinCAT BSD using StaticRoutes.xml 
![image](https://github.com/stlehmann/pyads/assets/10096753/2f85100e-8def-442e-9e0f-e3e1f742d7be)

3. Try this:
` plc = pyads.Connection(remote_plc_net_id, pyads.PORT_TC3PLC1)`

Hope this will help!

**Comment by chrisbeardy** [comment]
@X-Carolinii-X if this fixed your issue, please can you close this issue to help us manage the issues log, thank you
