### ISSUE TITLE
pyads not working on Python3.5

### ISSUE THREAD

**Issue by riatdyl** [stlehmann/pyads#367]
Hi
I've tried to use pyads on Python 3.5, but it was not working.
I had to use Python 3.7 in order to make it work.
It would be great if this information was mentioned in the documentation, because I hadn't seen it and I lost some time looking for the solution.
Thanks

**Comment by chrisbeardy** [comment]
yes we will update docs, and probably should update package so install on < python 3.7 errors

**Comment by chrisbeardy** [comment]
updated docs
