### ISSUE TITLE
PyAds Client running Local to 4026 Runtime on Windows

### ISSUE THREAD

**Issue by peterrathke** [stlehmann/pyads#385]
The following was tested with Python v3.12.3 Windows installer version
and PyAds version 3.4.0

In Tc3.1.4024 and previous versions. TcAdsDll.dll (which PyAds references) is installed in the following directory: “C:\TwinCAT\AdsApi\TcAdsDll\x64\TcAdsDll.dll”.

In Tc3.1.4026 install, the TcAdsDll.dll moved to “C:\Program Files (x86)\Beckhoff\TwinCAT\Common64\TcAdsDll.dll”.

Because of this directory change on 4026, I found that by editing the following file, i could get everything to work as expected.
"C:\Program Files\Python312\Lib\site-packages\pyads\pyads_ex.py"
![pyads_ex py File Edit](https://github.com/stlehmann/pyads/assets/74547565/18ed6195-1de2-49ba-a761-793b19025f57)

**Comment by chrisbeardy** [comment]
solved by #389
