### ISSUE TITLE
size_of_structure() does not work for structures with only 1 element

### ISSUE THREAD

**Issue by gerritsen-a** [stlehmann/pyads#418]
The first for-loop normally iterates over the different tuples, however if only 1 is given the for-loop will loop over the internals of the only tuple given.

**Comment by chrisbeardy** [comment]
Can you please post a minimal reproducible code example please?

**Comment by gerritsen-a** [comment]
thanks for the reply, the issue was on my side, I was not aware you can create a individual tuple in another tuple by adding a , behind it like:
`(('rVar', pyads.PLCTYPE_LREAL, 1),)`
apologies for raising a incorrect issue
