### ISSUE TITLE
Add proper support for multiple ams ports

### ISSUE THREAD

**Issue by pjaneck** [stlehmann/pyads#46]
Hey,

Right now all PLC connections run over the same ams port which is opend in the open_port method in ads.py. This is not desirerable for multi-connection-applications such as multi threading. It would be better to have one port for each new PLC connection.

Regards,
Peter

**Comment by stlehmann** [comment]
You mean the global port variable that is used in the open_port() function? Try the class approach. There each connection gets its own port number.
