### ISSUE TITLE
Set own AmsNetID

### ISSUE THREAD

**Issue by SmilingWorlock** [stlehmann/pyads#52]
Hello,

 I am trying to use pyads from within a docker container - this works fine, but since the AmsNetID is depentent on the IP Address, and the "internal" IP Address of a container is not necesseraly fixed, the AmsNetID changes a lot, resulting in routing problems on the remote device. Is there a way to set the AmsNetID indepently of the IP Address?

Best regards

**Comment by stlehmann** [comment]
There is no function in the Beckhoff ADS DLL that let's you choose your AmsNetID.

**Comment by dabrowne** [comment]
@stlehmann This functionality was added to upstream for the Linux lib here: https://github.com/Beckhoff/ADS/commit/c1bfedd25988468ac0f46e9cf0fff4d4be3ffa52

If you merge this commit (also present in my ADS fork) then we'd be able to provide this at least for Linux clients.

**Comment by stlehmann** [comment]
@dabrowne I didn't know of this one. Thanks. I will merge the commit and add this function to pyads.

**Comment by stlehmann** [comment]
@SmilingWorlock I added a new `set_local_address` function in the Release 2.2.13. Feel free to give it a go.
