### ISSUE TITLE
Target port not found   ADS Server not started (6)

### ISSUE THREAD

**Issue by f-scotto** [stlehmann/pyads#53]
Hi All, 
I am trying to control some variables on the PLC through pyads. Unfortunately I keep on receiving always the same error message. 'target port not found   ADS Server not started (6)'. Any ideas on how to get around this issue? Thanks a lot in advance. 

`import pyads

plc = pyads.Connection('10.2.9.142.1.1', 851)
plc.open()
plc.read_device_info()`

**Comment by stlehmann** [comment]
Are you on Linux ord Windows?

**Comment by f-scotto** [comment]
windows 10

**Comment by stlehmann** [comment]
Did you install Twincat on your PC and setup the routes to your target properly?

**Comment by f-scotto** [comment]
Yes, The route is setup correctly and the twinCAT is running on my machine correctly. I have uninstalled and installed the whole system but whenever i call the pyads.Connection('AMSNetId', 851) I get the same error message. (target port not found   ADS Server not started (6)). I cannot figure why!?

**Comment by f-scotto** [comment]
If I run the TcAdsTest I get this error message (see pic). 
![capture](https://user-images.githubusercontent.com/32665464/41984462-0bfecb26-7a31-11e8-9f11-1cf0bee37357.PNG)

**Comment by stlehmann** [comment]
This clearly looks like you've got an issue with the setup of your TwinCAT system. Unfortunately I can  not help you with this as it is not related to pyads. Maybe it helps to check if your Beckhoff ADS library is installed correctly on your system.

**Comment by Summerxiaxia623** [comment]
I got the same problem. Have you solved that?

**Comment by ishahak** [comment]
**Solution that worked for me:** 
In TwinCAT, project explorer, right-click your project name under "PLC" branch, and click _Change ADS Port_. it should be 851 normally. if it is not, update your Connection initialization accordingly.

**Comment by DuartePinguim** [comment]
Like @ishahak mention you need to go to your TwinCAT and see in what port PLC is working 

![Image](https://github.com/user-attachments/assets/239e1b34-5f76-4c24-89ca-0f29d8b06907)

![Image](https://github.com/user-attachments/assets/bf0b980b-1447-4e4d-9f23-bd04de9c1ac9)

Other thing you can use the constants of pyads

![Image](https://github.com/user-attachments/assets/6bf35a5e-b5e9-4b08-929d-cba9ce549be5)
