### ISSUE TITLE
Connection.open can't work on windows machines

### ISSUE THREAD

**Issue by sbberni** [stlehmann/pyads#54]
On windows machines "adsAddRoute" during plc.open() will called, so you get an RuntimeError:

![image](https://user-images.githubusercontent.com/41362313/42868651-28137a76-8a73-11e8-9cd1-2e847d2dd374.png)

Currently it's possible to get it work with the following workaround:

![image](https://user-images.githubusercontent.com/41362313/42868918-d0d93876-8a73-11e8-96d4-502353c6e1b5.png)

Please add a platform check in your open method like this:

![image](https://user-images.githubusercontent.com/41362313/42868991-0b26e2ee-8a74-11e8-889b-a96ce6427bc5.png)

**Comment by stlehmann** [comment]
Thanks for the feedback. Are you working with the latest pyads version?
