### ISSUE TITLE
pip install pyads leaves "src" folder in virtenv base folder

### ISSUE THREAD

**Issue by carstenschroeder** [stlehmann/pyads#59]
The remaining "src" folder with the adslib sources is not needed anymore but adds tons of git changes in a dev. environment (for e.g. HomeAssistant).

![image](https://user-images.githubusercontent.com/13978143/50559655-84728b00-0cf9-11e9-8552-a9f9a2904f03.png)

Could the src folder be deleted after install? 

Wouldn't it be better to change the name of the folder to e.g. ADSLibSrc or place it elsewhere during install, in order to prevent overlapping names?

**Comment by stlehmann** [comment]
This issue should be solved with version 3.0.10 b4da361862cea242782a657e7c29cd39fdc4aac4. The directory is now named adslib which should be distinct.
